apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: line1
    image: busybox:1.28
    command: ['sh', '-c', 'echo first line >> /work-dir/lines.txt']
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  - name: line2
    image: busybox:1.28
    command: ['sh', '-c', 'echo second line >> /work-dir/lines.txt']
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  - name: line3
    image: busybox:1.28
    command: ['sh', '-c', 'echo third line >> /work-dir/lines.txt']
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
