apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-python.fullname" . }}-credentials
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.user | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
