version: "3.4"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "10"
      tag: "{{.ImageName}}|{{.Name}}"

networks:
  loki:

services:
  app_python:
    image: igorparfenov/devops_lab:app_python_latest
    ports:
      - 80:5000
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
    <<: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget -O - http://localhost:5000/healthcheck | grep \"\\\"status\\\": \\\"success\\\"\" || exit 1"]

  app_php:
    image: igorparfenov/devops_lab:app_php_latest
    ports:
      - 81:80
    restart: always
    deploy:
      resources:
        limits:
          memory: 256m
    <<: *logging
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80/healthcheck.php | grep \"able to set test value in memcache\" || exit 1"]

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    <<: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - promtail-data:/var/lib/promtail/positions
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: always
    <<: *logging
    healthcheck:
      test: ["CMD", "bash", "-c", 'exec 4<>/dev/tcp/127.0.0.1/9080 && echo -e "GET /ready HTTP/1.0\n\n" >&4 && cat <&4 | grep "Ready"']

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana:/etc/grafana/provisioning:ro
    restart: always
    <<: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/healthz || exit 1"]

  prometheus:
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=14d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    <<: *logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]

volumes:
  promtail-data: {}
  prometheus-data: {}
