name: Markdown Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: Install markdownlint
        run: npm install markdownlint-cli
     
      - name: Run markdownlint
        run: npx markdownlint README.md DOCKER.md CI.md app_python/PYTHON.md app_php/PHP.md
